### ISSUE TITLE
Fix layout

### ISSUE THREAD

**Issue by lsolesen** [vih/fond-build#1]
After recent upgrades of Panopoly, the layout for our fund pages has broken. 

The layout for fond.vih.dk is based on Plate.

```
projects[plate][subdir] = contrib
projects[plate][version] = 1.x-dev
projects[plate][download][type] = git
projects[plate][download][revision] = 1d356218dc31678e2c7f0b28ac45c9bcdb27c12c
projects[plate][download][branch] = 7.x-1.x
```

![fond-layout](https://cloud.githubusercontent.com/assets/148026/6413555/1ca2187a-be91-11e4-92ea-45bcd44580db.png)

Plate should be upgraded to Radix 3.

**Comment by lsolesen** [comment]
@arshad Both Chef and Plate breaks in the recent Panopoly upgrades, so they are not compatible anymore.

**Comment by mglaman** [comment]
This is due to Radix layouts defining container-fluid while nothing "above" it defines a set width, will fix soon.

**Comment by lsolesen** [comment]
@mglaman Hm, it does not seem to have fixed the issue? It is still off on fond.vih.dk?

**Comment by lsolesen** [comment]
@mglaman As far as I can see, it is still not entirely fixed.

**Comment by mglaman** [comment]
@lsolesen I'm kind of confused.

This is what's in code for page.tpl.php,

``` html
    <div id="content" class="container">
      <a id="main-content"></a>
      <?php print render($page['content']); ?>
    </div>
  </div>
```

This is what's on production

``` html
    <div id="content">
      <a id="main-content"></a>
        <div class="region region-content">
    <div id="block-system-main" class="block block-system">
```

See vih/fond-build@a33831d5f850bd9d16168022e2c42c89ebc73860

**Comment by mglaman** [comment]
@lsolesen confirming that this is fixed locally, I think prod is just behind, or needs theme registry flushed.
